# Generated by Django 5.1.2 on 2024-10-19 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
